name: "Variable workflow"
on: push
jobs:
  print_job:
    name: "My first jobs"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Environment Variable
      env:
        USERNAME: "Vinoth"
        PASSWORD: "abcd@111"
      run: |
        echo "username is $USERNAME"
        echo "Password is $PASSWORD"

    -  name: "Echo Hello world"
       run: echo " Welcome to my github actions workflow "



